### ISSUE TITLE
algorand-sandbox-indexer  Error: unknown flag: --logfile

### ISSUE THREAD

**Issue by orsi-dev** [algorand/sandbox#35] opened 2021-03-24 16:43 UTC
hello,
i've found an error building the image of the indexer that restart the container in loop:

Follow the error:

algorand-sandbox-indexer | Connecting to algod:4001 (172.23.0.3:4001)
algorand-sandbox-indexer | saving to 'genesis.json'
algorand-sandbox-indexer | genesis.json         100% |********************************|  1697  0:00:00 ETA
algorand-sandbox-indexer | 'genesis.json' saved
algorand-sandbox-indexer | Error: unknown flag: --logfile

**Comment by winder** [comment] 2021-03-24 16:47
Sorry, this is a regression due to a change in the Indexer repo. It is fixed with https://github.com/algorand/sandbox/pull/33 so pulling the latest sandbox changes should resolve the problem.

**Closed by winder** 2021-03-24 16:47 UTC

**Comment by orsi-dev** [comment] 2021-03-24 16:48
great! 
thank you
